sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t thealpha06/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thealpha06/react-test npm test

after_success: 
  - docker build -t thealpha06/multi-client ./client
  - docker build -t thealpha06/multi-server ./server
  - docker build -t thealpha06/multi-worker ./worker
  - docker build -t thealpha06/multi-nginx ./nginx