language: generic
services:
  - docker

before_install:
  - docker build -t thealpha06/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thealpha06/react-test npm test

after_success: 
  - docker build -t thealpha06/multi-client:latest ./client
  - docker build -t thealpha06/multi-server:latest ./server
  - docker build -t thealpha06/multi-worker:latest ./worker
  - docker build -t thealpha06/multi-nginx:latest ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thealpha06/multi-client:latest
  - docker push thealpha06/multi-server:latest
  - docker push thealpha06/multi-worker:latest
  - docker push thealpha06/multi-nginx:latest

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-225149677297"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY